=== gabrielecosta/ledwall_webapp/ledwallmanager/src/main/resources/static/palinsesti/palinsesto.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT palinsesto (cartellone+)>
<!ATTLIST palinsesto id ID #REQUIRED>
<!ELEMENT cartellone (percorso, durata, azienda)>
<!ATTLIST cartellone id ID #REQUIRED>
<!ELEMENT percorso (#PCDATA)>
<!ELEMENT durata (#PCDATA)>
<!ELEMENT azienda (#PCDATA)>

=== gabrielecosta/ledwall_webapp/ledwallmanager/src/main/resources/static/palinsesti/palinsesto1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- INIZIO PALINSESTO -->
<!--palinsesto xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="palinsesto.xsd" id="P1"-->  
<!DOCTYPE palinsesto SYSTEM
        "/home/ivan/Unipa/Materie/Web Systems Design and Architecture/Consegne/Consegna 4/ledwallmanager/src/main/resources/static/palinsesto.dtd">
<palinsesto id="P1">
    <!-- CARTELLONE 1 -->
	<cartellone id="C1">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone1/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Palermo Football Club</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 1 -->
    
    <!-- CARTELLONE 2 -->
	<cartellone id="C2">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone2/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Rockstar Games</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 2 -->
    
    <!-- CARTELLONE 3 -->
	<cartellone id="C3">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone3/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Xeeon</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 3 -->

</palinsesto>
<!-- FINE PALISESTO -->
