=== gabrielecosta/ledwall_webapp/ledwallmanager/src/main/resources/static/palinsesti/palinsesto.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="palinsesto">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cartellone" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="percorso" type="xs:string"/>
              <xs:element name="durata" type="xs:integer"/>
              <xs:element name="azienda" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gabrielecosta/ledwall_webapp/ledwallmanager/src/main/resources/static/palinsesti/palinsesto4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- INIZIO PALINSESTO -->
<palinsesto xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="palinsesto.xsd" id="P4">  
    <!-- CARTELLONE 1 -->
	<cartellone id="C10">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone10/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Castelli's</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 1 -->
    
    <!-- CARTELLONE 2 -->
	<cartellone id="C5">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone5/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Orologeria Preziosi</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 2 -->
    
    <!-- CARTELLONE 3 -->
	<cartellone id="C3">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone3/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Xeeon</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 3 -->

</palinsesto>
<!-- FINE PALISESTO -->

=== gabrielecosta/ledwall_webapp/ledwallmanager/src/main/resources/static/palinsesti/palinsesto3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- INIZIO PALINSESTO -->
<palinsesto xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="palinsesto.xsd" id="P3">  
    <!-- CARTELLONE 1 -->
	<cartellone id="C7">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone7/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Pokemon</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 1 -->
    
    <!-- CARTELLONE 2 -->
	<cartellone id="C8">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone8/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Universit√† degli Studi di Palermo</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 2 -->
    
    <!-- CARTELLONE 3 -->
	<cartellone id="C9">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone9/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Castelli's</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 3 -->

</palinsesto>
<!-- FINE PALISESTO -->

=== gabrielecosta/ledwall_webapp/ledwallmanager/src/main/resources/static/palinsesti/palinsesto5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- INIZIO PALINSESTO -->
<palinsesto xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="palinsesto.xsd" id="P5">  
    <!-- CARTELLONE 1 -->
	<cartellone id="C2">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone2/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Rockstar Games</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 1 -->
    
    <!-- CARTELLONE 2 -->
	<cartellone id="C4">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone4/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Lavazza</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 2 -->
    
    <!-- CARTELLONE 3 -->
	<cartellone id="C10">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone10/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Castelli's</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 3 -->

</palinsesto>
<!-- FINE PALISESTO -->

=== gabrielecosta/ledwall_webapp/ledwallmanager/src/main/resources/static/palinsesti/palinsesto2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- INIZIO PALINSESTO -->
<palinsesto xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="palinsesto.xsd" id="P2">  
    <!-- CARTELLONE 1 -->
	<cartellone id="C4">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone4/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Lavazza</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 1 -->
    
    <!-- CARTELLONE 2 -->
	<cartellone id="C5">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone5/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Orologeria Preziosi</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 2 -->
    
    <!-- CARTELLONE 3 -->
	<cartellone id="C6">
		<!-- PERCORSO CARTELLONE -->
		<percorso>cartelloni/cartellone6/cartellone.html</percorso>
		<!-- LA DURATA DEVE ESSERE IN SECONDI -->
		<durata>30</durata>
		<!-- AZIENDA CHE COMMISSIONA IL CARTELLONE -->
		<azienda>Regione Siciliana</azienda>
	</cartellone>
    <!-- FINE CARTELLONE 3 -->

</palinsesto>
<!-- FINE PALISESTO -->
